### ISSUE TITLE
Feature request: Fixed list

### ISSUE THREAD

**Issue by GMib** [mikesilvo164/Aeon-Nox-SiLVO#91] opened 2019-07-27 19:17 UTC
please add "fixed list" option in right list view.

sorry for my bad english

**Comment by mikesilvo164** [comment] 2019-08-06 14:17
Can you be more specific?

Also why do you think I should add it?

**Comment by GMib** [comment] 2019-08-06 15:03
i replace list by fixedlist in View_506_RightList.xml  : `<control type="fixedlist" id="506">
					<focusposition>4</focusposition>` line 189
I hate having focus in last/first line, i can't see next/previous movie and I find it less beautiful.
i edit file myself, but i do edit again each update ;(
Sorry for not being more explicit, it's hard for me to argue in English

**Comment by mikesilvo164** [comment] 2019-08-07 15:03
If you mean this:
![Imgur](https://imgur.com/hn1cUTP.png)

Then sorry but no won't be added but if I add `<movement>5<movement>` and start scrolling on the center item then maybe I can add an option:
![Imgur](https://imgur.com/6lq67Ad.png)

**Comment by GMib** [comment] 2019-08-07 15:17
yes, it's what i mean, but i didn't know <movement>, i've just tested it and it's better ;)

**Comment by TacticalTurtleneck** [comment] 2019-08-07 15:20
Hi AKA HYPERIONzoom here,
I don't like GMib I much prefer the centred and locked focus when scrolling through titles. So much so that I exclusively use views that support it to the exclusion of some very good alternative views.

"...if I add <movement>5<movement> and start scrolling on the center item then maybe I can add an option"

I don't quite understand what you are proposing here. Would this result in a centred and locked focus? If so, could the option be included in other linear views? 
*linear = list-like, both vertical and horizontal

**Comment by GMib** [comment] 2019-08-07 15:26
yes focus remains centered except at the beginning or end of the list.
description of movement tag in https://kodi.wiki/view/Fixed_List_Container : This will make the focused position scroll again at the end of the list. (ie. <movement>6</movement> if there are only 6 items below the focus, the focus moves down to the bottom)

**Comment by TacticalTurtleneck** [comment] 2019-08-07 15:27
It's an option that has been present in other Aeon Nox skins but sadly have been unsupported in recent Kodi versions.

**Comment by mikesilvo164** [comment] 2019-08-07 15:29
@TacticalTurtleneck It is a lot easier to understand if you test the code but I'll see if I can explain it well enough with some pics.

The list starts focused at the top:
![Imgur](https://imgur.com/9HaOFBl.png)

Then when it hits the center item the list itself scrolls:
![Imgur](https://imgur.com/EQ00WD3.png)

Until you reach the end where it will move down the list again:
![Imgur](https://imgur.com/C8xKNdH.png)

**Comment by mikesilvo164** [comment] 2019-08-07 15:30
@TacticalTurtleneck What other Nox skins are you talking about?

**Comment by TacticalTurtleneck** [comment] 2019-08-07 15:31
> 
> 
> yes focus remains centered except at the beginning or end of the list.
> description of movement tag in https://kodi.wiki/view/Fixed_List_Container : This will make the focused position scroll again at the end of the list. (ie. 6 if there are only 6 items below the focus, the focus moves down to the bottom)

@GMib and @mikesilvo164: Yes, that's exactly what I'm after! However, I don't know how to implement that at this stage. Ideally I'd prefer the option to be included in the skin UI.

**Comment by TacticalTurtleneck** [comment] 2019-08-07 15:34
> 
> 
> @TacticalTurtleneck What other Nox skins are you talking about?

From memory it was in the original Aeon Nox 4 and Aeon Nox XBMCMania.

**Comment by mikesilvo164** [comment] 2019-08-07 15:38
@GMib & @TacticalTurtleneck I will push some finished code for you guys to test in a few minutes for just RightList view for now. 

Enable in view settings:
![Imgur](https://imgur.com/c0Fqw7P.png)

**Comment by mikesilvo164** [comment] 2019-08-07 15:39
You guys using leia or master branch?

**Comment by GMib** [comment] 2019-08-07 15:41
18.3 nightly for me

**Comment by TacticalTurtleneck** [comment] 2019-08-07 15:42
18.3 for me also.

**Comment by mikesilvo164** [comment] 2019-08-07 15:42
Ok I'll push to both leia and master then

**Comment by mikesilvo164** [comment] 2019-08-07 15:44
@GMib @TacticalTurtleneck Changes pushed and should be available now.

**Comment by TacticalTurtleneck** [comment] 2019-08-07 15:44
Thank you!

**Comment by TacticalTurtleneck** [comment] 2019-08-07 15:52
Gosh, that makes the world of a difference!! To be honest I was a little bummed that we were starting with RightList because it's been low on my favourites list- but now! It's been transformed with this one small tweak! I think this will be my new goto view for TV shows and keep Showcase for Movies.

Now if we could have the option to replace the titles with banners... ;) Just kidding. Baby steps. ;)

**Comment by GMib** [comment] 2019-08-07 15:54
thanks, there is a problem for me, black screen if i update, must crash kodi, i've set estuary by default then relaunch update, since aeon nox is not displayed, i've got error if i reinstall ;( trying to delete folder

**Comment by mikesilvo164** [comment] 2019-08-07 15:55
@GMib Exactly how are you doing the Git Pull? Are you using CLI or GUI like SmartGit?

**Comment by GMib** [comment] 2019-08-07 15:57
i've only use kodi update in extention menu. all work again after delete skin folder.

**Comment by mikesilvo164** [comment] 2019-08-07 15:57
@TacticalTurtleneck Banners won't fit. Would have to re-design the whole view.

Would be better to use InfoWall and switch to banners or create a whole new view which I am not to keen on doing ATM...

**Comment by GMib** [comment] 2019-08-07 16:03
strange kodi suggests me 7.0.3 update then i've already.

**Comment by TacticalTurtleneck** [comment] 2019-08-07 16:05
> 
> 
> @TacticalTurtleneck Banners won't fit. Would have to re-design the whole view.
> 
> Would be better to use InfoWall and switch to banners or create a whole new view which I am not to keen on doing ATM...

No problem, no problem.
I remember other Nox skins used banners in Tri-Panel which looked a treat- But I don't want to derail too much.

On topic of fixed list AKA centred and locked focus; if you were to add it to another view could you add it to "List". I mention it because it's often the only view available for some addons like Extras and YouTube.

**Comment by mikesilvo164** [comment] 2019-08-07 16:06
@GMib You can't update in Kodi. You are on GitHub not the Kodi forums.

I have updated the skin for testing in GitHub only.

You can check the instructions in the first post of my skin thread [HERE](https://forum.kodi.tv/showthread.php?tid=210069)

**Comment by mikesilvo164** [comment] 2019-08-07 16:12
> > @TacticalTurtleneck Banners won't fit. Would have to re-design the whole view.
> > Would be better to use InfoWall and switch to banners or create a whole new view which I am not to keen on doing ATM...
> 
> No problem, no problem.
> I remember other Nox skins used banners in Tri-Panel which looked a treat- But I don't want to derail too much.
> 
> On topic of fixed list AKA centred and locked focus; if you were to add it to another view could you add it to "List". I mention it because it's often the only view available for some addons like Extras and YouTube.

That's a little iffy here cause when the items are less than a full page the list would be centered in the list background and I don't think thats gonna look good at all. I would have to add a bunch of conditional slide animations to raise it but...

I'll begrudgingly look into adding it sometime in the near future possibly today, tomorrow or the following.

**Comment by GMib** [comment] 2019-08-07 16:14
ok, next kodi update will contain fixed option ? I edit file myself and wait future update.
thanks a lot ;)

**Comment by TacticalTurtleneck** [comment] 2019-08-07 16:17
> I'll begrudgingly look into adding it sometime in the near future possibly today, tomorrow or the following.

Take your time! I've been waiting for years for more views with fixed focus/banners and you know what? These a minor first-world quibbles. I can honestly get by with the way it is. It's just on my wishlist, that's all.

If you feel like adding it, I'd be over the moon. If not, c'est la vie.

**Comment by TacticalTurtleneck** [comment] 2019-08-07 16:19
> 
> 
> ok, next kodi update will contain fixed option ? I edit file myself and wait future update.
> thanks a lot ;)

You can download the latest version here on GitHub as a zip. Then in Kodi install the addon from zip file and you'll have the latest Git update. That's how I do it anyway.

**Comment by mikesilvo164** [comment] 2019-08-07 16:22
> You can download the latest version here on GitHub as a zip. Then in Kodi install the addon from zip file and you'll have the latest Git update. That's how I do it anyway.

You really should delete the skin folder first and open the zip file up  in winRar or something then remove -master from the end before installing from zip. Doing it like you mention could create multiple skin folders and that has caused some major issues in the past.

**Comment by GMib** [comment] 2019-08-07 16:25
In FAQ : The latest version can be downloaded from GitHub but DO NOT INSTALL through the addon manager. 
i prefer wait for repository, i'm not pressed i know how to edit file.

**Comment by TacticalTurtleneck** [comment] 2019-08-07 16:45
Ah, good to know. Thanks to you both.

I just reread the FAQ and I just want to confirm which addons folder you are referring to because there are several. Is it the one in Appdata > Roaming > Kodi > addons ?

**Comment by mikesilvo164** [comment] 2019-08-07 16:48
On Windows that is correct unless you run in portable mode then it would be the **Kodi install folder** > portable_data > addons

**Comment by mikesilvo164** [comment] 2019-08-07 16:52
Also I added that DO NOT INSTALL from add-on manager message to eliminate installation issues from some people thinking that just switching out a file makes things work when it is likely more than one file that needs replacing so unless you really know what you're doing, best practice is to delete the whole folder and re-install to eliminate possible mismatches causing problems.

**Comment by TacticalTurtleneck** [comment] 2019-08-07 16:53
That's good advice.

**Comment by mikesilvo164** [comment] 2019-08-07 16:54
Alternatively you could use SmartGit, which I use myself, to pull updates directly from GitHUb.

I can tell you how to set it up if you are interested.

**Comment by TacticalTurtleneck** [comment] 2019-08-07 16:56
Yes, tell me about this... SmartGit. I've heard mention of it. But there's probably instructions already made somewhere?

**Comment by mikesilvo164** [comment] 2019-08-07 16:57
Ok. First download from [HERE](https://www.syntevo.com/smartgit/download/)

**Comment by mikesilvo164** [comment] 2019-08-07 16:58
When you install make sure and choose free for non-commercial use or something like that.

**Comment by TacticalTurtleneck** [comment] 2019-08-07 16:59
Yes, I balked at the price. There's a free version I take it?

**Comment by mikesilvo164** [comment] 2019-08-07 17:00
Free install then when you open the program it asks if you want to be paid or non-commercial and you choose non-commercial.

If you have any questions during install and launch just let me know what you see and I'll tell you what to do :smiley:

**Comment by TacticalTurtleneck** [comment] 2019-08-07 17:18
OK, so I've added your SVN to SmartGit and I'm up to the part where I need to point SmartGit at my local folder. Should I point to my "AppData\Roaming\Kodi\addons" or "AppData\Roaming\Kodi\addons\skin.aeon.nox.silvo"

**Comment by mikesilvo164** [comment] 2019-08-07 17:20
Pretty sure just addons cause then it should clone the repo in an Aeon-Nox-SiLVO folder

**Comment by mikesilvo164** [comment] 2019-08-07 17:25
You are using clone in the repository menu and not add right?

**Comment by TacticalTurtleneck** [comment] 2019-08-07 17:29
I think so. Like this?
![01](https://user-images.githubusercontent.com/53827921/62644075-a5d0df00-b98c-11e9-9d87-357909693cf4.png)

**Comment by mikesilvo164** [comment] 2019-08-07 17:31
Yep looks good now you have to check out the leia branch cause that is what you are using.

If the branches window is open just double click it leia in the bottom left section.

**Comment by TacticalTurtleneck** [comment] 2019-08-07 17:34
I chose this option when setting up the clone. Is that right?
![2019-08-08 03_33_29-Clone](https://user-images.githubusercontent.com/53827921/62644428-69ea4980-b98d-11e9-8f9a-71d9e0fc8efa.png)

**Comment by mikesilvo164** [comment] 2019-08-07 17:35
Yeah but if it still says master after .git then you are not checked out on leia branch

**Comment by TacticalTurtleneck** [comment] 2019-08-07 17:37
In SmartGit:
![03](https://user-images.githubusercontent.com/53827921/62644545-b2a20280-b98d-11e9-9782-68254f475100.png)

And in my addons folder is deposits a folder named: Aeon-Nox-SiLVO.git

**Comment by mikesilvo164** [comment] 2019-08-07 17:38
Everything looks good so far. As long as that folder has a 16x9 folder, backgrounds, ect...

Ready to test updating?

**Comment by TacticalTurtleneck** [comment] 2019-08-07 17:39
Yes, please!

**Comment by mikesilvo164** [comment] 2019-08-07 17:41
Just to be sure we are all set the Aeon-Nox_SiLVO.git repo has (leia) in the brackets and not master right?

**Comment by TacticalTurtleneck** [comment] 2019-08-07 17:44
Yes, that first screenshot was when I mistakenly chose master instead of Leia. It now looks like this:
![04](https://user-images.githubusercontent.com/53827921/62645020-c39f4380-b98e-11e9-8541-00ad9500652c.png)

**Comment by mikesilvo164** [comment] 2019-08-07 17:46
Ok I just made a small change. Press pull button and then pull button unless it asks for something then you'll have to tell me what it is asking cause mine is already set up.

**Comment by TacticalTurtleneck** [comment] 2019-08-07 17:48
I presume "Rebase"?
![05](https://user-images.githubusercontent.com/53827921/62645349-622ba480-b98f-11e9-84b5-79011ebbe135.png)

**Comment by mikesilvo164** [comment] 2019-08-07 17:49
Yes! 😉

**Comment by TacticalTurtleneck** [comment] 2019-08-07 17:50
![image](https://user-images.githubusercontent.com/53827921/62645454-9901ba80-b98f-11e9-9b4c-26d9955041f7.png)

**Comment by mikesilvo164** [comment] 2019-08-07 17:53
rebase

**Comment by TacticalTurtleneck** [comment] 2019-08-07 17:54
OK so the 16x9 folder updated. Is that the folder you changed?

**Comment by mikesilvo164** [comment] 2019-08-07 17:57
Yeah I just moved that new fixed button for RightList below the Floor visible/hidden button instead of above it in the view settings.

Kodi needs to be restarted or you need to reload the skin for the changes to be seen.

You can test by checking the location of that button.

**Comment by TacticalTurtleneck** [comment] 2019-08-07 17:59
Won't Kodi still be running off the skin.aeon.nox.silvo folder that is also in addons?

**Comment by mikesilvo164** [comment] 2019-08-07 18:00
If you click log in the toolbar it should say Move position of button and show the line changes.

And that's it just hit pull and your updated with latest from Git and when you switch to Matrix just checkout the master branch and you're good to go.

**Comment by mikesilvo164** [comment] 2019-08-07 18:01
You need to delete all the other folders with silvo in it just have the Aeon-Nox-SiLVO folder.

**Comment by TacticalTurtleneck** [comment] 2019-08-07 18:02
Right. I just restarted Kodi and I can confirm that the "Fixed" toggle is now below Floor = visible! Well done!

**Comment by mikesilvo164** [comment] 2019-08-07 18:08
If you want to try your hand at modding the skin you can create a new working branch to play around with and just checkout the leia branch to go back to the unmodded one. You can also do a hard reset of the branch if you mess up something.

Alrighty then have a good day I'm off to spend some time with my annoying but sometimes wonderful kids.

👋

**Comment by TacticalTurtleneck** [comment] 2019-08-07 18:10
Sounds like a plan. It's actually extremely late for me here. 

So next time I want to update I open SmartGit and perform a Pull? Is there an auto update option?

**Comment by mikesilvo164** [comment] 2019-08-07 18:12
Yeah pull and rebase unless you chose set as default for repo.

I don't think there is an autoupdate option.

**Comment by TacticalTurtleneck** [comment] 2019-08-07 18:14
Thanks for all you help. Now go hang out with those kids! I'll get some sleep before sunrise... :)

**Comment by mikesilvo164** [comment] 2019-08-08 13:33
Since this issue is solved I'm gonna close it.

**Closed by mikesilvo164** 2019-08-08 13:33 UTC
